### ISSUE TITLE
parser take enums as keys for ngx-translate

### ISSUE THREAD

**Issue by sh4d0q** [svoboda-rabstvo/ngx-translate-lint#61]
Hi guys,

I have some issue because I use in projects a classic enums 

```
export enum CreatorState {
  NEW,
  DRAFT,
  VERSION,
}
```
html
```
<h1 *ngIf="creatorState === CreatorState.NEW">{{'carousel.details.title-new' | translate}}</h1>
```

and when I run **ngx-translate-lint** I have a lot of error like this:
```
                Key: 'CreatorState.NEW' doesn't exist in 'en.json'
                Key: 'CreatorState.NEW' doesn't exist in 'es.json'
```

I tried to ignore this file, but for parameter **ignore** I can use only one path, but I have a lot of situations like this.
I think It was very helpful to make some annotation to ignore line like this

**Comment by svoboda-rabstvo** [comment]
Hi @sh4d0q, thanks for your bugs. 

Can your please tell me arguments with use `ngx-translate-lint` and your current version of `ngx-translate-lint`.

Thanks a lot!

**Comment by svoboda-rabstvo** [comment]
However, ignore must be an array of paths

**Comment by sh4d0q** [comment]
I use version `1.7.1`,
and the config file:
```
{
  "rules": {
    "keysOnViews": "error",
    "zombieKeys": "warning",
    "misprint": "warning",
    "maxWarning": "0",
    "misprintCoefficient": "0.9"
  },
  "ast": "./",
  "project": "./apps/admin/src/app/**/*.{html,ts}",
  "languages": "./apps/admin/src/assets/i18n/*.json"
}
```
This is a problem with ignoring case sensitivity.I use `CreatorState` as enums and `creatorState` as translate key for ngx-translate, when I changed `creatorState` to `creatorStateMode` problem was disappeared

**Comment by svoboda-rabstvo** [comment]
`I tried to ignore this file, but for parameter ignore I can use only one path, but I have a lot of situations like this.
I think It was very helpful to make some annotation to ignore line like this`

I can create sepparate flag, with include array of keys with must be ignored.

**Comment by svoboda-rabstvo** [comment]
@sh4d0q. I released `1.7.2`. Can you check your keys on this version? If it doesn't help I create separate flag for you.

**Comment by sh4d0q** [comment]
Still doesn't work,

This is a specific case sensitivity when the key is used as enum and translation key

catch this out:
html
```
<div *ngIf="carousel?.publish && creatorState === CreatorState.VERSION">
            {{'creatorState.published' | translate}}
          </div>
```

```
Key: 'CreatorState.VERSION' doesn't exist in 'en.json'
Key: 'CreatorState.VERSION' doesn't exist in 'es.json'
```
the translations are only available for ```creatorState``` not for ```CreatorState``` because this is representative of the enum.

But the declaration of keys to ignore will be very helpful but this does not eliminate a problem

**Comment by svoboda-rabstvo** [comment]
I can't reproduce your problem :(

**Comment by sh4d0q** [comment]
try this,
en.json
```
"creatorState": {
    "new": "New",
    "draft": "Draft",
    "create": "Create",
    "create-draft": "Create draft",
    "version": "Version",
    "status": "Status",
    "published": "Published",
    "unpublished": "Unpublished",
    "has_draft": "Has draft",
    "active": "Active",
    "activate": "Activate",
    "inactive": "Inactive",
    "create-draft-from-copy": "Create draft from copy"
  },
```
ts
```
export class CarouselDetailsComponent {
  // export enums to use in template
  CreatorState = CreatorState;
```

```
export enum CreatorState {
  NEW,
  DRAFT,
  VERSION,
}
```
html (removed dependecy)
```
<nb-card>
    <nb-card-header class="header-page">
        <div class="row no-gutters">
            <div class="col-md-12 with-status">
                <h1 *ngIf="creatorState === CreatorState.NEW">{{'carousel.details.title-new' | translate}}</h1>
                <h1 *ngIf="creatorState === CreatorState.VERSION">{{'carousel.details.title-edit' | translate}}</h1>
                <h1 *ngIf="creatorState === CreatorState.DRAFT">{{'carousel.details.title-draft' | translate}}</h1>
                <div class="ml-4">
                    <div class="ccms-content-status--green"
                         *ngIf="creatorState === CreatorState.VERSION">
                        {{'creatorState.published' | translate}}
                    </div>
                    <div class="ccms-content-status--orange"
                         *ngIf="creatorState !== CreatorState.VERSION">
                        {{'creatorState.unpublished' | translate}}
                    </div>
                </div>
            </div>
        </div>
    </nb-card-header>
    <nb-card-body class="px-4" style="overflow: visible;">
        <div class="carousel-add">
            <div class="row no-gutters" *ngIf="creatorState !== CreatorState.DRAFT">
                <h4 class="col-12">{{'carousel.details.title' | translate}}</h4>
                <div class="col-md-4">
                    <form>
                        <div class="form-group">
                            <label class="input">{{'carousel.details.alias' | translate}}</label>
                            <input type="alias" class="form-control"
                                   [readonly]="creatorState !== CreatorState.NEW">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </nb-card-body>
</nb-card>
<nb-card>
    <nb-card-header>
        <div class="row no-gutters">
            <div class="col-md-12">
                <div class="d-flex flex-row justify-content-between">
                    <div class="d-flex flex-row justify-content-between align-items-baseline">
                        <h4 class="mb-0">{{'carousel.details.sub_title' | translate}}</h4>
                        <div class="inherit-size mx-4 ccms-version-number" *ngIf="creatorState === CreatorState.VERSION">
                            <nb-icon icon="info-outline" class="correct-alignment"></nb-icon>
                            {{('creatorState.version' | translate) }}
                        </div>
                    </div>
                    <div style="display: flex; flex-direction: row; align-items: center;">
                        <button class="btn btn-danger btn-outline-danger btn-no-outline" *ngIf="creatorState === CreatorState.VERSION">
                            {{'creatorState.draft' | translate}}
                        </button>
                        <span class="btn btn-danger btn-outline-danger btn-no-outline"*ngIf="creatorState === CreatorState.VERSION">
              {{'creatorState.create-draft' | translate}}
              </span>
                        <button class="btn btn-danger btn-outline-danger btn-no-outline" *ngIf="creatorState !== CreatorState.NEW">
                            {{'carousel.details.version' | translate}}
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </nb-card-header>
</nb-card>

<div class="row footer-action">
    <div class="px-2">
        <button *ngIf="creatorState === CreatorState.VERSION" type="submit" class="btn btn-danger btn-outline-danger btn-no-outline">
            {{'carousel.details.delete' | translate}}
        </button>
    </div>
    <div *ngIf="creatorState === CreatorState.DRAFT || creatorState === CreatorState.NEW">
          <span class="px-2">
            <button type="submit" class="btn btn-outline-success">
              {{'carousel.details.save-publish' | translate}}
            </button>
          </span>
    </div>
    <div *ngIf="creatorState === CreatorState.VERSION">
          <span class="px-2">
          </span>
    </div>
</div>

```

**Comment by svoboda-rabstvo** [comment]
Hi @sh4d0q, I released `1.7.3` it must be fixed your problem. Please check :)

**Comment by sh4d0q** [comment]
ok, now its works, thanks
